name: Build and deploy stage, beta, test release.

on:
  workflow_dispatch:
  push:
    branches: [stage, beta, test]
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: helsingborg-stad/municipio-deploy/4.0@master
      with:
        deploy-host: ${{ secrets.DEPLOY_REMOTE_HOST_STAGE }}
        deploy-port: ${{ secrets.DEPLOY_REMOTE_PORT_STAGE }}
        deploy-host-path: ${{ secrets.DEPLOY_REMOTE_PATH_STAGE  }}
        deploy-host-backup-path: ${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_STAGE }}
        deploy-host-user: ${{ secrets.DEPLOY_REMOTE_USER_STAGE }}
        deploy-host-user-key: ${{ secrets.DEPLOY_KEY_STAGE }}
        deploy-host-web-server-user: ${{ secrets.WEB_SERVER_USER_STAGE }}
        deploy-host-pagecache-path: ${{ secrets.DEPLOY_LS_PAGECACHE_PATH_STAGE }}
        php-version: ${{ secrets.PHP_VERSION }}
        kill-lsphp: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        acf-url: ${{ secrets.ACF_URL }}

  e2e-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8]
        total-shards: [8]
    steps:
      - name: Run Municipio E2E Tests
        uses: helsingborg-stad/municipio-e2e-action@v1
        with:
          sitemap-urls: ${{ vars.E2E_SITEMAP_URLS }}
          shard: ${{ matrix.shard }}
          total-shards: ${{ matrix.total-shards }}