name: E2E

on:
  workflow_run:
    workflows: ["Build and deploy stage, beta, test release."]
    types:
      - completed
jobs:
  call-workflow-passing-data:
    uses: helsingborg-stad/municipio-e2e-action/.github/workflows/test.yml@main
    with:
      sitemap_urls: https://visithelsingborg.hbgtest.se/sitemap.xml?pw_test
